### PR TITLE
feat: german translation

### PR DESCRIPTION
**Pull request by ralokt**
German translation!

One note: I translated "video map" as "Mauspfad", which pretty much means "mouse path". From my memory, that's what other clones call it in English as well - I may be wrong though, haven't used them in a while.

But, as an english-speaking user:
 - "mouse path" is the term I expected, and that would have instantly told me what to expect from the UI.
 - I also didn't immediately know what to expect from "video view". In context, I suspected it would probably be that, but had to look at it to confirm.

If you don't want to call it "mouse path" - it contains more than just the path, after all - perhaps just "path", "path view" or "event view" would be a better fit?

In any case, german translations for all candidates rn:
 "path" - "Pfad"
 "path view" - "Pfadansicht"
 "event view" - "Ereignisansicht"
 "video map" - "Videokarte"

### CODE REVIEW

**Comment by hgraceb** [comment]
Thank you very much for being able to help with the German translation.

However, there may be a few things that need to be changed slightly.

1. I think it would be more appropriate to translate it as "Video map", because, given the current page design, the user can switch between mouse path, click event, and opening area at the same time. Of course, if you still think "Mouse path" would be better, I'll collect other people's opinions and decide how to display them.

2. The translation of "Detect file drag" and "Select local file" is a bit too long, which makes them not fit in with the rest of the text on the menu page. I would suggest that the word "drag" be retained and the word "drop" be omitted.

3. In addition to translating the text, it is also necessary to add a determination of the browser's default language. This helps to improve the user's experience by displaying the German text by default when the user's browser is in German. You can find the relevant code here: [getDefaultLocale](https://github.com/hgraceb/flop-player/blob/vue/src/plugins/i18n.ts#L24).  Note, however, that the default language is always English, which takes care of the vast majority of users.

4. the translation of "marks" should preferably be followed by " (?)" which makes this option easier to understand

Finally, thank you again for your help.

**Comment by ralokt** [comment]
Only have a moment of time, but wanna give you my thoughts:

 - @1: I'm not necessarily set on "mouse path" - was just put off a bit by "video map". What do you think of "replay analysis"?
 - @2: Omitting "drop" makes it just a generic word for "pull" - I'm gonna have to think about that one.
 - @3: Noted, will do!
 - @4: I left it out as "Fragezeichen" literally means "question mark" (more literally "question symbol" :D), so it felt redundant - but yeah, I'll add it back for consistency.

**Comment by ralokt** [comment]
Note to future self and anyone who might be reading along: [Working link to getDefaultLocale](https://github.com/hgraceb/flop-player/blob/master/src/plugins/i18n.ts#L24)

**Comment by hgraceb** [comment]
After getting input from others, I decided to change "Video map" to "Mouse path", which helps the user to understand the meaning of the option when they first see it.

**Comment by ralokt** [comment]
I've pushed some progress!
  - @1: Leaving it as "Mauspfad" since that is the translation of "mouse path"
  - @2: I just made it the equivalent of "Drag and Drop" instead - I think that's the best use of limited space here.
  - @3: Done!
  - @4: Also done!

**Pull request merged**
